Object.freeze(
leagueDat = {
    home_bonus: 200,
    dp_for_yellow: 4,
    dp_for_red: 10 ,
    suspension_margin: 10,
    max_injury_length: 9,
    num_subs: 5,
    substitutions: 3,
    updtr_fitness_gain: 20,
    updtr_fitness_after_injury: 80,
    team_stats_total: 1,
    cup: 0
});
Object.freeze(
leagueAbilities = {
    AB_Goal: 50,
    AB_Assist: 35,
    AB_Victory_Random: 60,
    AB_Clean_Sheet: 50,
    AB_Ktk: 18,
    AB_Kps: 12,
    AB_Sht_On: 2,
    AB_Sht_Off: 0,
    AB_Sav: 12,
    AB_Defeat_Random: -60,
    AB_Concede: -8,
    AB_Yellow: -8,
    AB_Red: -20
});
Object.freeze(
leagueAbbreviations = {
    ape: "Apes_United",
    klm: "KLM_Royal_Club",
    uva: "Universidad_De_Valladolid",
    mac: "Machos_FC",
    bla: "Blade_Runners",
    esu: "ESMS_United",
    cra: "Crazy_Insomniacs"
});
Object.freeze(
tacticsDat = [
["TACTIC","N","Normal"],
["TACTIC","D","Defensive"],
["TACTIC","A","Attacking"],
["TACTIC","C","Counter_Attack"],
["TACTIC","L","Long_Ball"],
["TACTIC","P","Passing"],
"MULT N DF TK 1.0",
"MULT N DF PS 0.5",
"MULT N DF SH 0.3",
"MULT N DM TK 0.85",
"MULT N DM PS 0.75",
"MULT N DM SH 0.3",
"MULT N MF TK 0.3",
"MULT N MF PS 1.0",
"MULT N MF SH 0.3",
"MULT N AM TK 0.3",
"MULT N AM PS 0.85",
"MULT N AM SH 0.85",
"MULT N FW TK 0.3",
"MULT N FW PS 0.3",
"MULT N FW SH 1.0",
"MULT D DF TK 1.25",
"MULT D DF PS 0.5",
"MULT D DF SH 0.25",
"MULT D DM TK 1.13",
"MULT D DM PS 0.68",
"MULT D DM SH 0.25",
"MULT D MF TK 1.0",
"MULT D MF PS 0.75",
"MULT D MF SH 0.25",
"MULT D AM TK 0.75",
"MULT D AM PS 0.65",
"MULT D AM SH 0.5",
"MULT D FW TK 0.5",
"MULT D FW PS 0.25",
"MULT D FW SH 0.75",
"BONUS D L DF TK 0.25",
"MULT A DF TK 1.0",
"MULT A DF PS 0.5",
"MULT A DF SH 0.5",
"MULT A DM TK 0.5",
"MULT A DM PS 0.75",
"MULT A DM SH 0.68",
"MULT A MF TK 0.0",
"MULT A MF PS 1.0",
"MULT A MF SH 0.75",
"MULT A AM TK 0.0",
"MULT A AM PS 0.87",
"MULT A AM SH 1.13",
"MULT A FW TK 0.0",
"MULT A FW PS 0.75",
"MULT A FW SH 1.5",
"MULT C DF TK 1.0",
"MULT C DF PS 0.5",
"MULT C DF SH 0.25",
"MULT C DM TK 0.85",
"MULT C DM PS 0.85",
"MULT C DM SH 0.25",
"MULT C MF TK 0.5",
"MULT C MF PS 1.0",
"MULT C MF SH 0.25",
"MULT C AM TK 0.5",
"MULT C AM PS 0.85",
"MULT C AM SH 0.65",
"MULT C FW TK 0.5",
"MULT C FW PS 0.5 ",
"MULT C FW SH 1.0",
"BONUS C A MF SH 0.5",
"BONUS C A DF PS 0.25",
"BONUS C A DF SH 0.25",
"BONUS C P MF SH 0.5",
"BONUS C P DF PS 0.25",
"BONUS C P DF SH 0.25",
"MULT L DF TK 1.0",
"MULT L DF PS 0.25",
"MULT L DF SH 0.25",
"MULT L DM TK 0.75",
"MULT L DM PS 0.85",
"MULT L DM SH 0.38",
"MULT L MF TK 0.5",
"MULT L MF PS 1.0",
"MULT L MF SH 0.5 ",
"MULT L AM TK 0.45",
"MULT L AM PS 0.85",
"MULT L AM SH 0.9",
"MULT L FW TK 0.25",
"MULT L FW PS 0.5 ",
"MULT L FW SH 1.3",
"BONUS L C DF TK 0.25",
"BONUS L C DF PS 0.5",
"MULT P DF TK 1.0",
"MULT P DF PS 0.75",
"MULT P DF SH 0.3 ",
"MULT P DM TK 0.87",
"MULT P DM PS 0.87",
"MULT P DM SH 0.28",
"MULT P MF TK 0.25",
"MULT P MF PS 1.0",
"MULT P MF SH 0.25",
"MULT P AM TK 0.25",
"MULT P AM PS 0.87",
"MULT P AM SH 0.68",
"MULT P FW TK 0.25",
"MULT P FW PS 0.75",
"MULT P FW SH 1.0",
"BONUS P L MF SH 0.5",
"BONUS P L MF TK 0.5",
"BONUS P L FW SH 0.25"
]);
Object.freeze(
testRoster = [ 
  { name: 'U_Avrovroo',
    nationality: 'arg',
    age: 19,
    pref_side: 'RLC',
    st: 11,
    tk: 3,
    ps: 3,
    sh: 3,
    stamina: 39,
    ag: 38,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'U_Cledsedroe',
    nationality: 'eng',
    age: 28,
    pref_side: 'C',
    tk: 14,
    st: 3,
    ps: 5,
    sh: 7,
    stamina: 56,
    ag: 38,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'V_Iblakro',
    nationality: 'bra',
    age: 24,
    pref_side: 'LC',
    tk: 15,
    st: 3,
    ps: 8,
    sh: 7,
    stamina: 82,
    ag: 28,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'N_Prutri',
    nationality: 'hol',
    age: 19,
    pref_side: 'R',
    ps: 13,
    tk: 10,
    st: 3,
    sh: 7,
    stamina: 60,
    ag: 34,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'D_Bribs',
    nationality: 'ire',
    age: 20,
    pref_side: 'C',
    ps: 10,
    tk: 11,
    st: 3,
    sh: 5,
    stamina: 58,
    ag: 37,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'C_Zasa',
    nationality: 'den',
    age: 21,
    pref_side: 'R',
    ps: 9,
    tk: 11,
    st: 3,
    sh: 7,
    stamina: 43,
    ag: 23,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'Y_Stednuvr',
    nationality: 'spa',
    age: 19,
    pref_side: 'R',
    ps: 15,
    st: 3,
    tk: 9,
    sh: 7,
    stamina: 79,
    ag: 33,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'N_Ovruartoa',
    nationality: 'den',
    age: 20,
    pref_side: 'C',
    ps: 17,
    st: 3,
    tk: 6,
    sh: 7,
    stamina: 39,
    ag: 24,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'T_Ednam',
    nationality: 'saf',
    age: 23,
    pref_side: 'LC',
    ps: 17,
    st: 3,
    tk: 8,
    sh: 6,
    stamina: 39,
    ag: 25,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'V_Uvre',
    nationality: 'ire',
    age: 29,
    pref_side: 'R',
    ps: 11,
    st: 3,
    tk: 7,
    sh: 7,
    stamina: 75,
    ag: 37,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'J_Kavowpri',
    nationality: 'nor',
    age: 22,
    pref_side: 'L',
    ps: 13,
    sh: 10,
    tk: 8,
    st: 3,
    stamina: 81,
    ag: 28,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'M_Inya',
    nationality: 'bul',
    age: 21,
    pref_side: 'R',
    ps: 13,
    sh: 10,
    tk: 7,
    st: 3,
    stamina: 60,
    ag: 31,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'I_Orsecli',
    nationality: 'ger',
    age: 26,
    pref_side: 'R',
    ps: 13,
    sh: 9,
    tk: 7,
    st: 3,
    stamina: 49,
    ag: 23,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'S_Ogra',
    nationality: 'fra',
    age: 19,
    pref_side: 'R',
    ps: 11,
    sh: 11,
    tk: 9,
    st: 3,
    stamina: 69,
    ag: 35,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'Z_Shoz',
    nationality: 'bra',
    age: 26,
    pref_side: 'C',
    ps: 11,
    sh: 11,
    tk: 8,
    st: 3,
    stamina: 46,
    ag: 38,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'N_Ojhuryoeg',
    nationality: 'isr',
    age: 24,
    pref_side: 'RLC',
    sh: 17,
    st: 3,
    tk: 8,
    ps: 7,
    stamina: 70,
    ag: 22,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'K_Ovroodo',
    nationality: 'ger',
    age: 25,
    pref_side: 'RC',
    sh: 14,
    st: 3,
    tk: 5,
    ps: 8,
    stamina: 61,
    ag: 37,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'H_Kruvro',
    nationality: 'arg',
    age: 26,
    pref_side: 'C',
    sh: 14,
    st: 3,
    tk: 7,
    ps: 7,
    stamina: 47,
    ag: 26,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'P_Eblo',
    nationality: 'ger',
    age: 19,
    pref_side: 'R',
    sh: 12,
    st: 3,
    tk: 5,
    ps: 7,
    stamina: 43,
    ag: 32,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'H_Vepriks',
    nationality: 'ger',
    age: 24,
    pref_side: 'R',
    sh: 14,
    st: 3,
    tk: 7,
    ps: 7,
    stamina: 45,
    ag: 30,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 },
  { name: 'S_Omno',
    nationality: 'bul',
    age: 24,
    pref_side: 'L',
    sh: 15,
    st: 3,
    tk: 6,
    ps: 9,
    stamina: 38,
    ag: 30,
    st_ab: 300,
    tk_ab: 300,
    ps_ab: 300,
    sh_ab: 300,
    games: 0,
    saves: 0,
    tackles: 0,
    keypasses: 0,
    shots: 0,
    goals: 0,
    assists: 0,
    dp: 0,
    injury: 0,
    suspension: 0,
    fitness: 100 } ]);
